[features]
seeds = false
skip-lint = false
[programs.localnet]
token_contract28 = "BL9UPDzak7THnEALSgyKuJ5khE9pndFbFbW7rMYhheWQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/moueshouta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
